sudo: required
services: 
  - docker

before_install:
  - docker build -t krisnakris/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true krisnakris/react-test npm test

after_success:
  - docker build -t krisnakris/multi-client ./client
  - docker build -t krisnakris/multi-nginx ./nginx
  - docker build -t krisnakris/multi-server ./server
  - docker build -t krisnakris/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push krisnakris/multi-client
  - docker push krisnakris/multi-nginx
  - docker push krisnakris/multi-server
  - docker push krisnakris/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-687852198989
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
